language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"

services:
    - mongodb

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install pytest pytest-cov

# command to run tests
script:
#   nosetests
    python -m pytest --cov=.

after_success:
    coveralls
